// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"2cgrowth/goz/api/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method: http.MethodGet,
				Path: "/user/healthcheck",
				Handler: HealthCheck(serverCtx),
			},
		},
	)
}
